//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLogin
    {
        public int CId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPassword { get; set; }
        public string Location { get; set; }
        public string Mobile { get; set; }
        public string email { get; set; }
    }
}
