//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMasterYG
    {
        public int CustomerId { get; set; }
        public string GroupId { get; set; }
        public Nullable<byte> CustomerMasterTypeId { get; set; }
        public string YGSSAPCustomerCode { get; set; }
        public string CustomerName1 { get; set; }
        public string CustomerName2 { get; set; }
        public string CustomerName3 { get; set; }
        public string CustomerCountry { get; set; }
        public string PostalCode { get; set; }
        public string StateCode { get; set; }
        public string City { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string IndustryCode { get; set; }
        public string PAN { get; set; }
        public string TAN { get; set; }
        public string GSTNo { get; set; }
        public string CINNo { get; set; }
    }
}
