//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmployeeNo { get; set; }
        public string Name { get; set; }
        public string Nickname { get; set; }
        public string ShortName { get; set; }
        public string GlobalEmpNo { get; set; }
        public string YGSAccountCode { get; set; }
        public string DomainId { get; set; }
        public string YGSCostCenter { get; set; }
        public string CostCenter { get; set; }
        public Nullable<short> OrgDepartmentId { get; set; }
        public Nullable<byte> OrgOfficeId { get; set; }
        public string Sex { get; set; }
        public bool MaritalStatus { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public bool BoolContract { get; set; }
        public System.DateTime DOJ { get; set; }
        public Nullable<System.DateTime> EffectiveDOJ { get; set; }
        public Nullable<System.DateTime> ConfirmationDueDate { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<System.DateTime> DOL { get; set; }
        public Nullable<byte> DepartmentId { get; set; }
        public Nullable<short> GroupId { get; set; }
        public string DeptCode { get; set; }
        public string Grade { get; set; }
        public string Designation { get; set; }
        public Nullable<short> FunctionalRoleId { get; set; }
        public string EMail { get; set; }
        public string SerialNo { get; set; }
        public string BloodGroup { get; set; }
        public string HODEmpNo { get; set; }
        public bool BoolHOD { get; set; }
        public Nullable<byte> BlockId { get; set; }
        public Nullable<short> FloorId { get; set; }
        public string Qualification { get; set; }
        public string QualificationString { get; set; }
        public bool BoolFurnishedCertificates { get; set; }
        public string PrevEmployment { get; set; }
        public bool BoolExecutive { get; set; }
        public string MobileNo { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
        public Nullable<decimal> SpecialAllowance { get; set; }
        public Nullable<decimal> TransportAllowance { get; set; }
        public Nullable<decimal> TraineeAllowance { get; set; }
        public Nullable<decimal> PersonalPay { get; set; }
        public Nullable<decimal> ProfessionalAllowance { get; set; }
        public Nullable<int> PFNo { get; set; }
        public Nullable<int> FPFNo { get; set; }
        public string AccountsDetails { get; set; }
        public bool BoolESI { get; set; }
        public string ICICIAccNo { get; set; }
        public decimal MedAllBal { get; set; }
        public Nullable<short> PickupPointId { get; set; }
        public string HomePhone { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string EmergencyContactPerson { get; set; }
        public string EmergencyContactNo { get; set; }
        public bool BoolHasProximityCard { get; set; }
        public float PLStatus { get; set; }
        public Nullable<float> OldPLStatus { get; set; }
        public Nullable<float> LeavesDeductedFromFlexiDaily { get; set; }
        public Nullable<float> LeavesDeductedFromFlexiWeekly { get; set; }
        public byte RestrictedHolidaysAvailed { get; set; }
        public byte PaternityLeavesAvailed { get; set; }
        public string NameAsInPassport { get; set; }
        public string PassportNo { get; set; }
        public string PassportIssuedPlace { get; set; }
        public Nullable<System.DateTime> PassportIssuedDate { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public string AddressAsInPassport { get; set; }
        public string BirthPlace { get; set; }
        public string PanNo { get; set; }
        public string AadhaarNo { get; set; }
        public Nullable<bool> BoolKannadiga { get; set; }
        public Nullable<byte> CommunityId { get; set; }
        public string FathersName { get; set; }
        public string SpouseName { get; set; }
        public byte OrganizationId { get; set; }
        public bool BoolIntranetEnabled { get; set; }
        public string UAN { get; set; }
        public Nullable<byte> ExpenseCategoryId { get; set; }
        public bool BoolExpatriate { get; set; }
        public string PWD { get; set; }
        public Nullable<int> RoleId { get; set; }
    }
}
