//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public string Grade1 { get; set; }
        public string GroupId { get; set; }
        public string Designation { get; set; }
        public byte Hierarchy { get; set; }
        public decimal SumInsured { get; set; }
        public decimal SumInsuredDependentParents { get; set; }
        public decimal PersonalAccidentSumInsured { get; set; }
        public string JobStatus { get; set; }
        public float TSSkillFactor { get; set; }
        public byte TEVComfortLevel { get; set; }
        public decimal TEVOutOfPocketAllowance { get; set; }
        public decimal TEVOffshoreAllowance { get; set; }
        public decimal TEVDayTripAllowance { get; set; }
        public bool BoolInUse { get; set; }
    }
}
