//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRDispatchLocation
    {
        public byte DispatchLocationId { get; set; }
        public string DispatchLocation { get; set; }
        public byte XOrder { get; set; }
        public bool BoolInUse { get; set; }
    }
}
