//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MPRDetail()
        {
            this.MPRIncharges = new HashSet<MPRIncharge>();
            this.MPROfferDetails = new HashSet<MPROfferDetail>();
            this.MPRRevisions = new HashSet<MPRRevision>();
            this.MPRStatusTracks = new HashSet<MPRStatusTrack>();
        }
    
        public int RequisitionId { get; set; }
        public string DocumentNo { get; set; }
        public string SubmittedBy { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public Nullable<System.DateTime> XXXCommercialOfferReceivedDate { get; set; }
        public string XXXOfferDetailsMailedBy { get; set; }
        public Nullable<System.DateTime> XXXOfferDetailsMailedOn { get; set; }
        public Nullable<System.DateTime> XXXOfferDetailsViewedByCheckerOn { get; set; }
        public Nullable<System.DateTime> XXXOfferDetailsViewedByApproverOn { get; set; }
        public Nullable<System.DateTime> XXXMaterialReceiptDate { get; set; }
        public string XXXRemarks { get; set; }
        public Nullable<decimal> XXXEstimatedCost { get; set; }
        public Nullable<decimal> XXXPreviousPOPrice { get; set; }
        public Nullable<byte> XXXPurchaseTypeId { get; set; }
        public Nullable<byte> XXXPreferredVendorTypeId { get; set; }
        public Nullable<byte> XXXStatusId { get; set; }
        public Nullable<decimal> XXXPurchaseCost { get; set; }
        public string DocumentDescription { get; set; }
    
        public virtual MPRPreferredVendorType MPRPreferredVendorType { get; set; }
        public virtual MPRPurchaseType MPRPurchaseType { get; set; }
        public virtual MPRStatu MPRStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRIncharge> MPRIncharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPROfferDetail> MPROfferDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRRevision> MPRRevisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRStatusTrack> MPRStatusTracks { get; set; }
    }
}
