//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRDocumentation
    {
        public int DocumentationId { get; set; }
        public int RevisionId { get; set; }
        public byte DocumentationDescriptionId { get; set; }
        public byte NoOfSetsApproval { get; set; }
        public byte NoOfSetsFinal { get; set; }
    
        public virtual MPRDocumentationDescription MPRDocumentationDescription { get; set; }
        public virtual MPRRevision MPRRevision { get; set; }
    }
}
