//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRIncharge
    {
        public int InchargeId { get; set; }
        public int RequisitionId { get; set; }
        public int RevisionId { get; set; }
        public string Incharge { get; set; }
        public bool CanClearTechnically { get; set; }
        public bool CanClearCommercially { get; set; }
        public bool CanReceiveMailNotification { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool DeleteFlag { get; set; }
    
        public virtual MPRDetail MPRDetail { get; set; }
        public virtual MPRRevision MPRRevision { get; set; }
    }
}
