//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPROfferDetail
    {
        public int OfferId { get; set; }
        public int RequisitionId { get; set; }
        public string VendorName { get; set; }
        public System.DateTime OfferMailedOn { get; set; }
        public string Remarks { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredOn { get; set; }
    
        public virtual MPRDetail MPRDetail { get; set; }
    }
}
