//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRPAApprover
    {
        public int ApproverId { get; set; }
        public int PAId { get; set; }
        public byte ApproverLevel { get; set; }
        public string Approver { get; set; }
        public string ApproversRemarks { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    
        public virtual MPRPADetail MPRPADetail { get; set; }
    }
}
