//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRPAVendor
    {
        public int VendorId { get; set; }
        public int PAId { get; set; }
        public string Vendor { get; set; }
        public bool BoolSelectedVendor { get; set; }
    
        public virtual MPRPADetail MPRPADetail { get; set; }
    }
}
