//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRPADetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MPRPADetail()
        {
            this.MPRItemDetails_X = new HashSet<MPRItemDetails_X>();
            this.MPRPAApprovers = new HashSet<MPRPAApprover>();
            this.MPRPAVendors = new HashSet<MPRPAVendor>();
        }
    
        public int PAId { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> RequestedOn { get; set; }
        public Nullable<byte> PurchaseTypeId { get; set; }
        public Nullable<byte> PurchaseModeId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<decimal> TargetedSpendAmount { get; set; }
        public Nullable<decimal> PurchaseCost { get; set; }
        public string PackagingForwarding { get; set; }
        public string Taxes { get; set; }
        public string Freight { get; set; }
        public string Insurance { get; set; }
        public string DeliveryCondition { get; set; }
        public string ShipmentMode { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<short> CreditDays { get; set; }
        public string Warranty { get; set; }
        public string BankGuarantee { get; set; }
        public string LDPenaltyTerms { get; set; }
        public string SpecialInstructions { get; set; }
        public string FactorsForImports { get; set; }
        public string SpecialRemarks { get; set; }
        public string SuppliersReference { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRItemDetails_X> MPRItemDetails_X { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRPAApprover> MPRPAApprovers { get; set; }
        public virtual MPRPAPurchaseMode MPRPAPurchaseMode { get; set; }
        public virtual MPRPAPurchaseType MPRPAPurchaseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRPAVendor> MPRPAVendors { get; set; }
    }
}
