//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRReminderTracking
    {
        public int ReminderId { get; set; }
        public int MPRCCId { get; set; }
        public string MailTo { get; set; }
        public string MailAddressType { get; set; }
        public Nullable<System.DateTime> MailSentOn { get; set; }
        public Nullable<System.DateTime> ReminderSentOn { get; set; }
        public Nullable<System.DateTime> AcknowledgedOn { get; set; }
        public string AcknowledgementRemarks { get; set; }
        public bool DeleteFlag { get; set; }
    
        public virtual MPRCommunication MPRCommunication { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
