//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRTargetedSpendSupportingDoc
    {
        public int DocumentId { get; set; }
        public int RevisionId { get; set; }
        public string DocumentFilename { get; set; }
    
        public virtual MPRRevision MPRRevision { get; set; }
    }
}
