//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRVendorDetail
    {
        public int VendorDetailsId { get; set; }
        public int RevisionId { get; set; }
        public int Vendorid { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string RemovedBy { get; set; }
        public Nullable<System.DateTime> RemovedDate { get; set; }
        public bool RemoveFlag { get; set; }
    
        public virtual MPRRevision MPRRevision { get; set; }
        public virtual VendorMaster VendorMaster { get; set; }
    }
}
