//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQCommunication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RFQCommunication()
        {
            this.RFQReminderTrackings = new HashSet<RFQReminderTracking>();
        }
    
        public int RfqCCid { get; set; }
        public Nullable<int> RfqItemsId { get; set; }
        public int RfqRevisionId { get; set; }
        public string RemarksFrom { get; set; }
        public string RemarksTo { get; set; }
        public Nullable<bool> SendEmail { get; set; }
        public Nullable<bool> SetReminder { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public System.DateTime RemarksDate { get; set; }
        public string Remarks { get; set; }
        public bool DeleteFlag { get; set; }
    
        public virtual RFQItem RFQItem { get; set; }
        public virtual RFQRevision RFQRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFQReminderTracking> RFQReminderTrackings { get; set; }
    }
}
