//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RFQItem()
        {
            this.RFQCommunications = new HashSet<RFQCommunication>();
            this.RFQDocuments = new HashSet<RFQDocument>();
            this.RFQItemsInfoes = new HashSet<RFQItemsInfo>();
        }
    
        public int RFQItemsId { get; set; }
        public int RFQRevisionId { get; set; }
        public int MPRItemDetailsid { get; set; }
        public double QuotationQty { get; set; }
        public string VendorModelNo { get; set; }
        public string HSNCode { get; set; }
        public string RequestRemarks { get; set; }
        public bool DeleteFlag { get; set; }
    
        public virtual MPRItemInfo MPRItemInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFQCommunication> RFQCommunications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFQDocument> RFQDocuments { get; set; }
        public virtual RFQRevision RFQRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFQItemsInfo> RFQItemsInfoes { get; set; }
    }
}
