//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RFQMaster()
        {
            this.RFQRevisions = new HashSet<RFQRevision>();
        }
    
        public int RfqMasterId { get; set; }
        public Nullable<int> MPRRevisionId { get; set; }
        public string RFQNo { get; set; }
        public Nullable<int> RFQUniqueNo { get; set; }
        public int VendorId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool DeleteFlag { get; set; }
    
        public virtual MPRRevision MPRRevision { get; set; }
        public virtual VendorMaster VendorMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFQRevision> RFQRevisions { get; set; }
    }
}
