//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQStatu
    {
        public int RfqStatusId { get; set; }
        public int RfqRevisionId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Remarks { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public bool DeleteFlag { get; set; }
    
        public virtual RFQRevision RFQRevision { get; set; }
    }
}
