//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_CategoryAttributes
    {
        public int CatAttributeid { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> AttributeId { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        public virtual Test_AttributeMaster Test_AttributeMaster { get; set; }
    }
}
