//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_CategoryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test_CategoryMaster()
        {
            this.Test_CategoryMaster1 = new HashSet<Test_CategoryMaster>();
            this.Test_ItemMaster = new HashSet<Test_ItemMaster>();
        }
    
        public int Categoryid { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<byte> BuyergroupId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> Deleteflag { get; set; }
    
        public virtual MPRBuyerGroup MPRBuyerGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_CategoryMaster> Test_CategoryMaster1 { get; set; }
        public virtual Test_CategoryMaster Test_CategoryMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_ItemMaster> Test_ItemMaster { get; set; }
    }
}
