//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorRFQTerm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorRFQTerm()
        {
            this.RFQVendorTerms = new HashSet<RFQVendorTerm>();
        }
    
        public int VendorTermsid { get; set; }
        public int TermsCategoryId { get; set; }
        public int VendorID { get; set; }
        public string Terms { get; set; }
        public Nullable<int> Indexno { get; set; }
        public bool deleteFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFQVendorTerm> RFQVendorTerms { get; set; }
        public virtual TermsCategory TermsCategory { get; set; }
        public virtual VendorMaster VendorMaster { get; set; }
    }
}
