//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteRFQReminderTracking
    {
        public int Reminderid { get; set; }
        public int rfqccid { get; set; }
        public string ReminderTo { get; set; }
        public Nullable<System.DateTime> MailsSentOn { get; set; }
        public Nullable<System.DateTime> Acknowledgementon { get; set; }
        public string AcknowledgementRemarks { get; set; }
        public bool DeleteFlag { get; set; }
    
        public virtual RemoteRFQCommunication RemoteRFQCommunication { get; set; }
    }
}
