//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteRFQRevision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RemoteRFQRevision()
        {
            this.RemoteRFQCommunications = new HashSet<RemoteRFQCommunication>();
            this.RemoteRFQDocuments = new HashSet<RemoteRFQDocument>();
            this.RemoteRFQItems = new HashSet<RemoteRFQItem>();
            this.RemoteRFQStatus = new HashSet<RemoteRFQStatu>();
            this.RemoteRFQVendorTerms = new HashSet<RemoteRFQVendorTerm>();
        }
    
        public int rfqRevisionId { get; set; }
        public int rfqMasterId { get; set; }
        public int RevisionNo { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime RFQValidDate { get; set; }
        public string PackingForwarding { get; set; }
        public string ExciseDuty { get; set; }
        public string SalesTax { get; set; }
        public string Freight { get; set; }
        public string Insurance { get; set; }
        public string CustomsDuty { get; set; }
        public Nullable<int> ShipmentModeid { get; set; }
        public Nullable<int> PaymentTermDays { get; set; }
        public string PaymentTermRemarks { get; set; }
        public string BankGuarantee { get; set; }
        public Nullable<int> DeliveryMinWeeks { get; set; }
        public Nullable<int> DeliveryMaxWeeks { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public Nullable<bool> SyncStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemoteRFQCommunication> RemoteRFQCommunications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemoteRFQDocument> RemoteRFQDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemoteRFQItem> RemoteRFQItems { get; set; }
        public virtual RemoteRFQMaster RemoteRFQMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemoteRFQStatu> RemoteRFQStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemoteRFQVendorTerm> RemoteRFQVendorTerms { get; set; }
    }
}
