//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteRFQCommunication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RemoteRFQCommunication()
        {
            this.RemoteRFQReminderTrackings = new HashSet<RemoteRFQReminderTracking>();
        }
    
        public int RfqCCid { get; set; }
        public Nullable<int> RfqItemsId { get; set; }
        public int RfqRevisionId { get; set; }
        public string RemarksFrom { get; set; }
        public string RemarksTo { get; set; }
        public Nullable<bool> SendEmail { get; set; }
        public Nullable<bool> SetReminder { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public System.DateTime RemarksDate { get; set; }
        public string Remarks { get; set; }
        public bool DeleteFlag { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public Nullable<bool> SyncStatus { get; set; }
    
        public virtual RemoteRFQItem RemoteRFQItem { get; set; }
        public virtual RemoteRFQRevision RemoteRFQRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemoteRFQReminderTracking> RemoteRFQReminderTrackings { get; set; }
    }
}
