//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VSCMEntities : DbContext
    {
        public VSCMEntities()
            : base("name=VSCMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RemoteRFQCommunication> RemoteRFQCommunications { get; set; }
        public virtual DbSet<RemoteRFQDocument> RemoteRFQDocuments { get; set; }
        public virtual DbSet<RemoteRFQItem> RemoteRFQItems { get; set; }
        public virtual DbSet<RemoteRFQItemsInfo> RemoteRFQItemsInfoes { get; set; }
        public virtual DbSet<RemoteRFQMaster> RemoteRFQMasters { get; set; }
        public virtual DbSet<RemoteRFQReminderTracking> RemoteRFQReminderTrackings { get; set; }
        public virtual DbSet<RemoteRFQRevision> RemoteRFQRevisions { get; set; }
        public virtual DbSet<RemoteRFQStatu> RemoteRFQStatus { get; set; }
        public virtual DbSet<RemoteRFQVendorTerm> RemoteRFQVendorTerms { get; set; }
        public virtual DbSet<RemoteVendorMaster> RemoteVendorMasters { get; set; }
        public virtual DbSet<RemoteVendorRFQTerm> RemoteVendorRFQTerms { get; set; }
        public virtual DbSet<RemoteVendorUserMaster> RemoteVendorUserMasters { get; set; }
    }
}
