//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteRFQVendorTerm
    {
        public int RFQTermsid { get; set; }
        public int RFQversionId { get; set; }
        public int VendorTermsid { get; set; }
        public string updatedBY { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool DeleteFlag { get; set; }
    
        public virtual RemoteRFQRevision RemoteRFQRevision { get; set; }
        public virtual RemoteVendorRFQTerm RemoteVendorRFQTerm { get; set; }
    }
}
