//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteVendorRFQTerm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RemoteVendorRFQTerm()
        {
            this.RemoteRFQVendorTerms = new HashSet<RemoteRFQVendorTerm>();
        }
    
        public int VendorTermsid { get; set; }
        public int TermsCategoryId { get; set; }
        public int VendorID { get; set; }
        public string Terms { get; set; }
        public Nullable<int> Indexno { get; set; }
        public bool deleteFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemoteRFQVendorTerm> RemoteRFQVendorTerms { get; set; }
    }
}
